// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEditor;


public class EditorCommon {
	public static void Save() {
		GameObject dataObject = EditorData.GetDataObject ();
		if (dataObject == null) {
			Debug.Log ("Editor Data prefab is null.");
			return;
		}
		
		//PrefabUtility.ReplacePrefab (this.gameObject, dataObject);
		PropertyModification[] temp = new PropertyModification[1];
		temp [0] = new PropertyModification ();
		temp [0].target = dataObject;
		PrefabUtility.SetPropertyModifications (dataObject, temp);
		EditorApplication.SaveAssets ();
		EditorData.Instance.AfterSave ();
	}

	public static void SaveFormula() {
		GameObject dataObject = FormulaData.GetDataObject ();
		if (dataObject == null) {
			Debug.Log ("FormulaData Data prefab is null.");
			return;
		}
		
		//PrefabUtility.ReplacePrefab (this.gameObject, dataObject);
		PropertyModification[] temp = new PropertyModification[1];
		temp [0] = new PropertyModification ();
		temp [0].target = dataObject;
		PrefabUtility.SetPropertyModifications (dataObject, temp);
		EditorApplication.SaveAssets ();
		FormulaData.Instance.AfterSave ();
	}

	public static void SaveStateMachine() {
		GameObject dataObject = StateMachineData.GetDataObject ();
		if (dataObject == null) {
			Debug.Log ("StateMachineData Data prefab is null.");
			return;
		}
		
		//PrefabUtility.ReplacePrefab (this.gameObject, dataObject);
		PropertyModification[] temp = new PropertyModification[1];
		temp [0] = new PropertyModification ();
		temp [0].target = dataObject;
		PrefabUtility.SetPropertyModifications (dataObject, temp);
		EditorApplication.SaveAssets ();
		StateMachineData.Instance.AfterSave ();
	}
}

