///SignKeys 工具自动生成代码，仅供调用，无需编辑
using System;
using System.Collections.Generic;
namespace FormulaBase {
	public class ConfigKeys {
		public static Dictionary<string, string> NamePaths = new Dictionary<string, string> {
			{ "char_cos", "char/_config/"},
			{ "char_info", "char/_config/"},
			{ "capsule", "config/"},
			{ "capsule_combination", "config/"},
			{ "daily_task", "config/"},
			{ "experience", "config/"},
			{ "skill", "config/"},
			{ "skilleffect", "config/"},
			{ "store", "config/"},
			{ "system_sfx", "config/"},
			{ "talk", "config/"},
			{ "upgrade_info", "config/"},
			{ "items", "items/_config/"},
			{ "notedata", "note/_config/"},
			{ "pet", "servant/_config/"},
			{ "cindellera_song1", "stage/stage_v1/json/"},
			{ "lets_dance_boys1", "stage/stage_v1/json/"},
			{ "lucky_love1", "stage/stage_v1/json/"},
			{ "masquerade1", "stage/stage_v1/json/"},
			{ "monkey_song1", "stage/stage_v1/json/"},
			{ "test_fire1", "stage/stage_test/"},
			{ "test_item1", "stage/stage_test/"},
			{ "test_jump_hit1", "stage/stage_test/"},
			{ "test_quick1", "stage/stage_test/"},
			{ "test_s011", "stage/stage_test/"},
			{ "test_s031", "stage/stage_test/"},
			{ "test_s041", "stage/stage_test/"},
			{ "test_s051", "stage/stage_test/"},
			{ "test_scene_event1", "stage/stage_test/"},
			{ "amacha1", "stage/stage_v1/json/"},
			{ "an_unfortunate_incident1", "stage/stage_v1/json/"},
			{ "an_unfortunate_incident_easy1", "stage/stage_v1/json/"},
			{ "bgm_maoudamashii_cyber121", "stage/stage_v1/json/"},
			{ "break_dawn1", "stage/stage_v1/json/"},
			{ "cheerful1", "stage/stage_v1/json/"},
			{ "cheerful_easy1", "stage/stage_v1/json/"},
			{ "confession1", "stage/stage_v1/json/"},
			{ "confession_easy1", "stage/stage_v1/json/"},
			{ "cyber_121", "stage/stage_v1/json/"},
			{ "day_by_day1", "stage/stage_v1/json/"},
			{ "delvge1", "stage/stage_v1/json/"},
			{ "delvge_normal1", "stage/stage_v1/json/"},
			{ "evolution1", "stage/stage_v1/json/"},
			{ "greed1", "stage/stage_v1/json/"},
			{ "ikz1", "stage/stage_v1/json/"},
			{ "iyaiya1", "stage/stage_v1/json/"},
			{ "jump_test1", "stage/stage_v1/json/"},
			{ "midstream_jam1", "stage/stage_v1/json/"},
			{ "night_wander1", "stage/stage_v1/json/"},
			{ "offset_test1", "stage/stage_v1/json/"},
			{ "osoujibiyori1", "stage/stage_v1/json/"},
			{ "plastic_adventure1", "stage/stage_v1/json/"},
			{ "pops_up_the_mind_wings1", "stage/stage_v1/json/"},
			{ "pops_up_the_mind_wings_easy1", "stage/stage_v1/json/"},
			{ "press_test1", "stage/stage_v1/json/"},
			{ "psycho_chemical1", "stage/stage_v1/json/"},
			{ "raintable1", "stage/stage_v1/json/"},
			{ "raintable2", "stage/stage_v1/json/"},
			{ "raintable3", "stage/stage_v1/json/"},
			{ "shall_we_meet1", "stage/stage_v1/json/"},
			{ "shall_we_meet_easy1", "stage/stage_v1/json/"},
			{ "snow_and_rain1", "stage/stage_v1/json/"},
			{ "starry_eyed1", "stage/stage_v1/json/"},
			{ "stream1", "stage/stage_v1/json/"},
			{ "surviving1", "stage/stage_v1/json/"},
			{ "telekinesis1", "stage/stage_v1/json/"},
			{ "time_scrawl1", "stage/stage_v1/json/"},
			{ "today_is_a_gift1", "stage/stage_v1/json/"},
			{ "tutorial1", "stage/stage_v1/json/"},
			{ "tutorial_new1", "stage/stage_v1/json/"},
			{ "viento_del_sol1", "stage/stage_v1/json/"},
			{ "wounderful_pain1", "stage/stage_v1/json/"},
			{ "achievement", "stage/_config/"},
			{ "stage", "stage/_config/"},
			{ "stage_value", "stage/_config/"},
		};
	}
}