///SignKeys 工具自动生成代码，仅供调用，无需编辑
using System;
using System.Collections.Generic;
namespace FormulaBase {
	public class ConfigKeys {
		public static Dictionary<string, string> NamePaths = new Dictionary<string, string> {
			{ "char_cos", "char/_config/"},
			{ "char_info", "char/_config/"},
			{ "character", "char/_config/"},
			{ "clothing", "char/_config/"},
			{ "cube", "config/"},
			{ "cube_combination", "config/"},
			{ "experience", "config/"},
			{ "skill", "config/"},
			{ "skilleffect", "config/"},
			{ "soundeffect", "config/"},
			{ "store", "config/"},
			{ "talk", "config/"},
			{ "items", "items/_config/"},
			{ "notedata", "note/_config/"},
			{ "pet", "servant/_config/"},
			{ "achievement", "stage/_config/"},
			{ "stage", "stage/_config/"},
			{ "stage_value", "stage/_config/"},
			{ "cindellera_song1", "stage/stage_old/"},
			{ "lets_dance_boys1", "stage/stage_old/"},
			{ "lucky_love1", "stage/stage_old/"},
			{ "masquerade1", "stage/stage_old/"},
			{ "monkey_song1", "stage/stage_old/"},
			{ "test_fire1", "stage/stage_test/"},
			{ "test_item1", "stage/stage_test/"},
			{ "test_jump_hit1", "stage/stage_test/"},
			{ "test_quick1", "stage/stage_test/"},
			{ "test_s011", "stage/stage_test/"},
			{ "test_s031", "stage/stage_test/"},
			{ "test_s041", "stage/stage_test/"},
			{ "test_s051", "stage/stage_test/"},
			{ "test_scene_event1", "stage/stage_test/"},
			{ "amacha1", "stage/stage_v1/json/"},
			{ "an_unfortunate_incident1", "stage/stage_v1/json/"},
			{ "bgm_maoudamashii_cyber121", "stage/stage_v1/json/"},
			{ "cheerful1", "stage/stage_v1/json/"},
			{ "confession1", "stage/stage_v1/json/"},
			{ "delvge1", "stage/stage_v1/json/"},
			{ "evolution1", "stage/stage_v1/json/"},
			{ "greed1", "stage/stage_v1/json/"},
			{ "pops_up_the_mind_wings1", "stage/stage_v1/json/"},
			{ "raintable1", "stage/stage_v1/json/"},
			{ "shall_we_meet1", "stage/stage_v1/json/"},
			{ "stream1", "stage/stage_v1/json/"},
			{ "surviving1", "stage/stage_v1/json/"},
			{ "telekinesis1", "stage/stage_v1/json/"},
			{ "tutorial_new1", "stage/stage_v1/json/"},
			{ "wounderful_pain1", "stage/stage_v1/json/"},
		};
	}
}