// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace GameLogic {
	public class DestorySelf : DoNothing {
		public override void Do (Spine.AnimationState state, int trackIndex, int loopCount) {
			SpineMountController smc = this.gameObject.GetComponent<SpineMountController> ();
			if (smc != null) {
				smc.DestoryDynamicObjects ();
			}

			this.gameObject.SetActive (false);
			string name = this.gameObject.name.Split ('(') [0];
			//Debug.Log("name to be destroy is: "+name);
			if (SceneObjectController.Instance != null && SceneObjectController.Instance.SceneObjectPool != null && SceneObjectController.Instance.SceneObjectPool.ContainsKey (name)) {
				SceneObjectController.Instance.SceneObjectPool [name] = null;
			}

			GameObject.Destroy (this.gameObject);

			// TODO:Destroy by animation, maintains object list here 
//			SpineActionController sac;
		}
	}
}
