// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace GameLogic {
	public class DoNothing {
		public int idx;
		public GameObject gameObject;

		public void SetIdx(int idx) {
			this.idx = idx;
		}

		public void SetGameObject(GameObject obj) {
			this.gameObject = obj;
		}

		public virtual void Do (Spine.AnimationState state, int trackIndex, int loopCount) {
		}
	}
}
