// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections;
using FormulaBase;
using Spine;

namespace GameLogic {
	public class NormalNodeOnAttacked : DoNothing {
		private const int ANI_LEN = 2;

		public override void Do (TrackEntry entry) {
			MusicData mcData = StageBattleComponent.Instance.GetMusicDataByIdx (this.idx);
			string aniName = mcData.nodeData.boss_hurt;
			if (aniName == null || aniName.Length < ANI_LEN) {
				aniName = ACTION_KEYS.HURT;
			}
			
			Boss.Instance.Play (aniName);
		}
	}
}
