// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace GameLogic {
	public class OnNormalAttack : DoNothing {
	public override void Do (Spine.AnimationState state, int trackIndex, int loopCount) {
			/*
			GirlActionController ga = this.gameObject.GetComponent<GirlActionController> ();
			if (ga == null) {
				return;
			}
		
			MeshRenderer render = this.gameObject.GetComponent<MeshRenderer> ();
			if (render == null) {
				return;
			}
		
			int aidx = ga.GetActionIndex () + 1;
			render.sortingOrder = aidx;
			*/
		}
	}
}