// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using Spine;

namespace GameLogic {
	public class UnActiveObject : DoNothing {
		public override void Do (TrackEntry entry) {
			SpineActionController.Play (ACTION_KEYS.COMEIN, this.gameObject);
			this.gameObject.SetActive (false);
		}
	}
}
