// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using Spine;

namespace GameLogic {
	public class UnLockActionProtect : DoNothing {
		public override void Do (TrackEntry entry) {
			SpineActionController sac = this.gameObject.GetComponent<SpineActionController> ();
			if (sac != null) {
				sac.SetProtectLevel (0);
				sac.SetCurrentActionName(null);
			}
		}
	}
}
